## 本地图片上传路径
local:
  path: static
mysql:
  path: 127.0.0.1
  port: "3306"
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: newbee
  username: root
  password: 170416
  max-idle-conns: 0
  max-open-conns: 0
  log-mode: ""
  log-zap: false
postgresql:
  driverName: postgres
  host: localhost
  port: '5432'
  database: health_demo
  username: postgres
  password: '170416'
  dbSslmode: disable
system:
  addr: 8888
  db-type: postgresql
  oss-type: local
  use-multipoint: false
  iplimit-count: 15000
  iplimit-time: 3600
zap:
  level: info
  format: console
  prefix: '[newbee_mall]'
  director: log
  showLine: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true
